# Window configuration
[window]
title = "Alacritty"
dynamic_title = true
startup_mode = "Windowed"

# Font configuration
[font]
normal = { family = "Roboto Mono", style = "Medium" }
bold = { family = "Roboto Mono", style = "Bold" }
italic = { family = "Roboto Mono", style = "Italic" }
size = 16.0


# Color scheme (Nord-inspired)
[colors]
primary = { background = "#111111", foreground = "#ffffff" }

[colors.normal]
black = "#3B4252"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#88C0D0"
white = "#E5E9F0"

[colors.bright]
black = "#4C566A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#ECEFF4"

